[package]
name = "contract-util"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["thiserror"]
onchain = ["casper-contract/no-std-helpers"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
casper-contract = { git = "ssh://git@github.com/BoostyLabs/casper-node.git", rev = "0246a4ab4874bfce71b5a9591dba20d54c54bd51", default-features = false, features = ["test-support"] }
casper-types    = { git = "ssh://git@github.com/BoostyLabs/casper-node.git", rev = "0246a4ab4874bfce71b5a9591dba20d54c54bd51" }

num_enum = { version = "0.5.7", default-features = false }

once_cell = { version = "1.12.0", default-features = false }
thiserror = { version = "1.0.31", optional = true }
k256 = { version = "0.10.4", default-features = false, features = ["pem"] }
base16 = { version = "0.2.1", default-features = false }

[build-dependencies]
cfg_aliases = "0.1.1"
